# Delta vector generative ML model

This Generative Machine Learning model generates an 'expected delta vector' from pairs of samples **before** and **after** vaccination.

Given a new pair of samples, it predicts which one is before vaccination and which one is after vaccination by comparing its delta vector to the 'expected delta vector'.

In [4]:
import main_delta_vector_generative_model
import sample_distances

main_delta_vector_generative_model.detect_vaccine(
    # The distance function used during prediction to compare the sample pair to the 'expected delta vector'.
    dist_func=sample_distances.lp(2),
    # Limit the data below to just the first n pairs. (defaults to None)
    data_limit=None,
    # List of pairs of samples.
    # Each pair consists of two samples from the same person, one of which before the vaccine, the other after.
    X=[
        ('cdr3.a.A_2017_2018_d_00_53535.ann', 'cdr3.a.A_2017_2018_d_07_11143.ann'),
        ('cdr3.a.B_2017_2018_d_00_56786.ann', 'cdr3.a.B_2017_2018_d_09_50844.ann'),
        ('cdr3.a.C_2017_2018_d_07_48996.ann', 'cdr3.a.C_2017_2018_d_00_26898.ann'),
        ('cdr3.a.D_2017_2018_d_00_45294.ann', 'cdr3.a.D_2017_2018_d_07_55841.ann'),
        ('cdr3.a.E_2017_2018_d_00_94077.ann', 'cdr3.a.E_2017_2018_d_07_54569.ann'),
    ],
    # labels
    # 1 -> oriented as (before vaccine, after vaccine)
    # 0 -> oriented as (after vaccine, before vaccine)
    y=[1, 1, 0, 1, 1],
)


got delta vecs
[1 2 3 4]
[0]
[0 2 3 4]
[1]
[0 1 3 4]
[2]
[0 1 2 4]
[3]
[0 1 2 3]
[4]
[(array([1]), [True]), (array([1]), [True]), (array([0]), [False]), (array([1]), [True]), (array([1]), [True])]

accuracy: 1.0


# Delta vector ML model

This Machine Learning model is trained on delta vectors showing the immune system change from **before** vaccination to **after** vaccination.

The model then takes a pair of samples and predicts which of the two samples came before the vaccine and which came after.

In [ ]:
import main_delta_vector_ml_model

main_delta_vector_ml_model.detect_vaccine(
    # Limit the data below to just the first n pairs. (defaults to None)
    limit=3,
    X=[
        ('cdr3.a.A_2017_2018_d_00_53535.ann','cdr3.a.A_2017_2018_d_07_11143.ann'),
        ('cdr3.a.B_2017_2018_d_00_56786.ann','cdr3.a.B_2017_2018_d_09_50844.ann'),
        ('cdr3.a.C_2017_2018_d_00_26898.ann','cdr3.a.C_2017_2018_d_07_48996.ann'),
        ('cdr3.a.D_2017_2018_d_00_45294.ann','cdr3.a.D_2017_2018_d_07_55841.ann'),
        ('cdr3.a.E_2017_2018_d_00_94077.ann','cdr3.a.E_2017_2018_d_07_54569.ann'),
    ],
    # labels
    # 1 -> oriented as (before vaccine, after vaccine)
    # 0 -> oriented as (after vaccine, before vaccine)
    y=[1] * 5,
)


# Vaccine detection ML model

This Machine Learning model guesses whether a person has or has not taken the vaccine.

  1. The model trains on almost all the given samples except for 1 or 2 which are withheld for testing purposes.
  2. The model then predicts whether the withheld samples were before or after the vaccine.
  3. These results are compared to the correct answer.
  4. The simulation may run multiple times and outputs an accuracy.

In [ ]:
import main_vaccine_detection_ml_model

main_vaccine_detection_ml_model.detect_vaccine(
    # Limit each sample to the top n CDR3s before running the ML model.
    cdr3_limit=500,
    # Limit the number of samples below to the following number. (defaults to None)
    data_limit=None,
    # list of samples (file names) being used to train the model
    X=[
        'cdr3.a.A_2017_2018_d_00_53535.ann',
        'cdr3.a.A_2017_2018_d_07_11143.ann',
        'cdr3.a.B_2017_2018_d_00_56786.ann',
        'cdr3.a.B_2017_2018_d_09_50844.ann',
        'cdr3.a.C_2017_2018_d_00_26898.ann',
        'cdr3.a.C_2017_2018_d_07_48996.ann',
        'cdr3.a.D_2017_2018_d_00_45294.ann',
        'cdr3.a.D_2017_2018_d_07_55841.ann',
        'cdr3.a.E_2017_2018_d_00_94077.ann',
        'cdr3.a.E_2017_2018_d_07_54569.ann',
    ],
    # list of whether each sample was taken before or after the vaccine.
    # 0 -> before the vaccine
    # 1 -> after the vaccine
    # This list is parallel to X, meaning that, for example, the third value in y corresponds to the third value in X.
    y=[
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
    ],
)


# Vaccine Delta vector

Take TCR-repertoire after vaccine minus TCR-repertoire before vaccine to obtain a TCR-repertoire "delta vector" that represents the gained immunity from being exposed to the vaccine.

We obtain one delta vector per person and then average them into a single Delta vector.

In [ ]:
import main_delta_vector

main_delta_vector.compute_vaccine_delta_vector(
    # Samples of people before and after vaccination.
    # Use a list of (before_vaccine, after_vaccine) file names pairs.
    file_names=[        
        ('cdr3.a.A_2017_2018_d_00_53535.ann', 'cdr3.a.A_2017_2018_d_07_11143.ann'),
        ('cdr3.a.B_2017_2018_d_00_56786.ann', 'cdr3.a.B_2017_2018_d_09_50844.ann'),
        ('cdr3.a.C_2017_2018_d_00_26898.ann', 'cdr3.a.C_2017_2018_d_07_48996.ann'),
        ('cdr3.a.D_2017_2018_d_00_45294.ann', 'cdr3.a.D_2017_2018_d_07_55841.ann'),
        ('cdr3.a.E_2017_2018_d_00_94077.ann', 'cdr3.a.E_2017_2018_d_07_54569.ann'),
    ],
)


# Find Common CDR3s

Find CDR3 sequences common across multiple samples.

This could be useful for finding CDR3s that are common to many people, or for finding CDR3s that persist in the same person over a long period of time.  A CDR3 common to many people could potentially be antigen-binding for a widespread virus.

In [ ]:
import main_common_cdr3s

main_common_cdr3s.find_common_cdr3s(
    # the file names of the samples you want to compare
    file_names=[
        'cdr3.a.A_2017_2018_d_00_53535.ann',
        'cdr3.a.B_2017_2018_d_00_32483.ann',
        'cdr3.a.C_2017_2018_d_00_26898.ann',
        'cdr3.a.D_2017_2018_d_00_45294.ann',
        'cdr3.a.E_2017_2018_d_00_94077.ann',
    ],
    # only use the top n highest-frequency cdr3s in each sample (default=None). Put None for no restriction.
    n=4000,
)


# Clustering CDR3s

Perform hierarchical clustering on the CDR3s in a sample.

Given a sample, a distance function on CDR3 pairs, and a limit n, cluster the top n CDR3s in the sample according to the distance between them.

This analysis is useful for finding highly-similar top CDR3s in a sample, which are great candidates for potential mutations, and "sister" CDR3s that combat the same virus.

In [ ]:
import main_cluster_cdr3s
import cdr3_distances

main_cluster_cdr3s.cluster_cdr3s(
    # the file name of the sample you want to analyze
    file_name='cdr3.a.A_2017_2018_d_00_53535.ann',
    # the distance function you want to use on each CDR3 pair
    # values: hamming, levenshtein, sorensen, jaccard
    dist_func=cdr3_distances.hamming,
    # the ngram 'n' to use on the CDR3 sequences before applying the distance function (defaults to 1)
    n_gram_len=1,
    # the number of CDR3s you want to look at. it will cluster the top n CDR3s in the sample.
    n=30,
)


# Closest n CDR3s

Find the n closest CDR3s to a given CDR3.

Given a CDR3, a sample, a distance function, and a limit "n", find the n CDR3s in the sample that are closest to the given CDR3 according to the given distance function.

If you have a specific CDR3 that is important for combatting a virus, this analysis could be useful for finding other CDR3s that may also defend against the virus.  This analysis is also useful for finding CDR3s that may have arisen from a mutation.

In [ ]:
import main_n_closest_cdr3s
import cdr3_distances

main_n_closest_cdr3s.get_n_closest_cdr3s(
    # the file name of the sample you want to analyze
    file_name='cdr3.a.A_2017_2018_d_00_53535.ann',
    # the CDR3 sequence
    cdr3='cVVSAFQAGTALIf',
    # the number of closest CDR3s you want to output
    n=20,
    # the distance function you want to use on each pair of CDR3s
    # values: hamming, levenshtein, sorensen, jaccard
    dist_func=cdr3_distances.hamming,
    # the ngram 'n' to use on the CDR3 sequences before applying the distance function (defaults to 1)
    n_gram_len=1,
)


# Curve fitting CDR3 frequencies

Given a sample, we graph its CDR3 frequencies and then fit a piecewise Zipf and exponential decay curve to the points.

We report the R^2 score which indicates how good the fit is.

In [ ]:
import main_piecewise_curve_fitting

print('computation starting...\n\n')
main_piecewise_curve_fitting.fit_curve(
    # file name of the sample whose frequencies you want to analyze
    file_name='cdr3.a.A_2017_2018_d_00_53535.ann',
    # the number of CDR3s you want to analyze (put None if you want them all).
    num_cdr3s=50,
    # reasonable starting guesses for the fit method
    # param 1: 's' negative exponent of (x**-s/zetac(s) + c) Zipf func
    # param 2: 'c' vertical displacement of (x**-s/zetac(s) + c) Zipf func
    # param 3: the piecewise midpoint cutoff boundary
    # param 4: 'a' multiplier in (a * x**b + c) exponential decay func
    # param 5: 'b' exponent in (a * x**b + c) exponential decay func
    # param 6: 'c' constant in (a * x**b + c) exponential decay func
    initial_param_guesses=[6.1, 1.1, 3.1, 60000.1, -1.1, 1.1],
)
print('\n\ncomputation complete.')


# Sample to Sample distance ladder

Look at the distance (amount of change) between pairs of samples.

Various distance functions can be used to compute a distance between a pair of samples.  In this analysis you can choose which distance function suits your objective.

The number immediately to the right of a sample represents the distance between that sample and the one immediately below it.  The number TWO spots to the right of the sample represents the distance between that sample and the one TWO spots below it.  And so forth.

In [ ]:
import main_sample_to_sample
import sample_distances

print('computation starting...\n\n')
main_sample_to_sample.calculate_combination(
    # distance function used to compute the distance between each pair of samples
    # values: l2 (Euclidean), lp(p) (input any integer >= 1 for p), linfty, jaccard, weighted_jaccard, jensen_shannon
    dist_func=sample_distances.lp(1),
    # list the samples you want to compare. they will be compared in the order you put them.
    file_names=[
        'cdr3.b.A_2017_2018_d_00_53535.ann',
        'cdr3.b.A_2017_2018_d_07_11143.ann',
        'cdr3.b.A_2017_2018_d_28_44887.ann',
        'cdr3.b.A_2017_2018_m_04_73516.ann',
        # 'cdr3.b.A_2019_2020_d_00_20857.ann',
    ],
    # the maximum number of columns in the distance ladder
    ladder_width=3,
)
print('\n\ncomputation complete.')


# Average sample distance

Find the average distance between pairs of samples.

Given a list of samples, find the distance between each possible sample pair, and then take the average of those numbers.  This is useful to get an idea of what a "normal" distance might be in the context of the samples you are currently looking at and the current distance function you are using.

In [ ]:
import main_average_sample_distance
import sample_distances

print('computation starting...\n\n')
main_average_sample_distance.calculate_combination(
    # distance function used to compute the distance between each pair of samples
    # values: l2 (Euclidean), lp(p) (input any integer >= 1 for p), linfty, jaccard, weighted_jaccard, jensen_shannon
    dist_func=sample_distances.linfty,
    # samples you want to compare. order does not matter.
    file_names={
        'A': ['cdr3.a.A_2017_2018_d_00_53535.ann'],
        'B': ['cdr3.a.B_2017_2018_d_00_32483.ann'],
        'C': ['cdr3.a.C_2017_2018_d_00_26898.ann'],
        # 'D': ['cdr3.a.D_2017_2018_d_00_45294.ann'],
        # 'E': ['cdr3.a.E_2017_2018_d_00_94077.ann'],
    },
)
print('\n\ncomputation complete.')


# CDR3s to Sample

Use distances between a small number of CDR3s in order to guess which sample they came from.

For example, we could have 5 people and 1 sample from each person.  We then remove a CDR3 at random from one of these samples (and to be fair, we remove the same CDR3 from all the other samples if it occurs).  We then look at the distance between this CDR3 and the remaining CDR3s in the samples, and we see which sample is closest.  We **guess** that this is the sample that the CDR3 was originally removed from.  Finally, we rerun the whole process `num_trials` times and report the percentage of guesses that were correct (the **accuracy**).

In [ ]:
import main_cdr3s_to_sample

print('computation starting...')
main_cdr3s_to_sample.calculate_combination(
    # the file names of the samples you want to guess among
    file_names={
        'A': ['cdr3.a.A_2000_2001_d_00_47407.ann'],
        'B': ['cdr3.a.B_2017_2018_d_00_32483.ann'],
        'C': ['cdr3.a.C_2017_2018_d_00_26898.ann'],
        # 'D': ['cdr3.a.D_2017_2018_d_00_45294.ann'],
        # 'E': ['cdr3.a.E_2017_2018_d_00_94077.ann'],
    },
    # the number of times to run the simulation per sample
    num_trials_per_sample=3,
    # the ngram 'n' to use on the CDR3 sequences before applying the distance function
    n_gram_len=1,
    # the distance function to use on pairs of CDR3s
    # values: hamming, levenshtein, sorensen, jaccard
    inner_dist_func_name='jaccard',
    # the aggregation function to use on cdr3 distances in order to obtain a single cdr3--sample distance
    dist_agg_func_name='min',
    # the number of CDR3s to use per guess. more CDR3s is more information and should increase accuracy, but also increase computation time
    num_cdr3s=1,
)
print('computation complete.')


# CDR3 Lifespan

Run the following cell to get a graph of cdr3 frequencies changing over time.

In [ ]:
import data_utils
import main_cdr3_lifespan

print('computation starting...')
sample = data_utils.get_cdr3_counter_from_file('s', 'cdr3.b.A_2019_2020_d_00_20857.ann')
cdr3s = sample.get_sorted_cdr3s(limit=4) # <- top 4 cdr3 sequences occuring in cdr3.b.A_2019_2020_d_00_20857.ann
main_cdr3_lifespan.calculate_one(
    # list of cdr3 sequences you want to graph
    cdr3s=cdr3s,
    # Sample file names from which to grab cdr3 frequency data.
    # Typically all files are from the SAME person.
    # Each file will correspond to a single date on the x-axis of the graph.
    file_names=[
      'cdr3.b.A_2017_2018_d_00_53535.ann',
      'cdr3.b.A_2017_2018_d_07_11143.ann',
      'cdr3.b.A_2017_2018_d_28_44887.ann',
      'cdr3.b.A_2017_2018_m_04_73516.ann',
      'cdr3.b.A_2019_2020_d_00_20857.ann',
    ],
    # whether or not to display the cdr3 legend in the graph
    show_legend=True,
)
print('computation complete.')
